53 create a parser for nchs bundle of bundles creating the java objects with correct type in a list
nightingaleproject/VRDR_javalib pull request #57
Opened 2023-07-07 18:41 UTC by consultantusa

2023-07-07 18:53 UTC, johnarleyburns requested changes

2023-07-07 18:53 UTC, johnarleyburns commented on src/main/java/edu/gatech/chai/VRDR/messaging/BaseMessage.java
> +    public static List<? extends Bundle> parseBundleOfBundles(Class clazz, VRDRFhirContext ctx, String filePath, String bundleString) {
This method needs documentation here, and also a usage example in the README.

2023-07-07 18:53 UTC, johnarleyburns commented on src/test/java/edu/gatech/VRDR/MessagingTest.java
> +        List listOfMessages = BaseMessage.parseBundleOfBundles(DemographicsCodingMessage.class, ctx, "src/test/resources/json/DemographicsCodingMessage.json", null);
Also test parsing a string without a file, because this is the typical use case.

2023-07-07 18:53 UTC, johnarleyburns commented on src/main/java/edu/gatech/chai/VRDR/messaging/BaseMessage.java
> +    public static List<? extends Bundle> parseBundleOfBundles(Class clazz, VRDRFhirContext ctx, String filePath, String bundleString) {
This is a good start, but needs a few changes:

There doesn't need to be a Class clazz argument here, all message types should be parsed.  The return type should be List<BaseMessage>.  What you want to do is like the C# class:
1. Extract each bundle from the list of bundles string
2. Check the bundle type and parse based on type for any of the message type subclasses of BaseMessage
3. Assemble a list of BaseMessage, adding each message from step 2
4. Return the List<BaseMessage>

2023-07-26 22:24 UTC, consultantusa commented
hapi-fhir-master\hapi-fhir-base\src\main\java\ca\uhn\fhir\parser\ParserState.java needs to be tweaked to make this a working function. Adding "!definition.getName().equals("Bundle") && !myResourceType.getName().contains("Bundle") &&" to the conditional statement at line 1079 of the above file would escape the DataFormatException "wrongResourceTypeFound" that prevented parsing nested bundles.

if (!definition.getName().equals("Bundle") && !myResourceType.getName().contains("Bundle") && !StringUtils.equals(theLocalPart, definition.getName())) {
					throw new DataFormatException(Msg.code(1814)
							+ myContext
									.getLocalizer()
									.getMessage(
											ParserState.class,
											"wrongResourceTypeFound",
											definition.getName(),
											theLocalPart));
				}

2023-07-26 22:42 UTC, johnarleyburns commented
Can you subclass ParserState or the entire Parser class and override as
needed?

On Wed, Jul 26, 2023 at 5:24 PM Thomas Nguyen ***@***.***>
wrote:

> hapi-fhir-master\hapi-fhir-base\src\main\java\ca\uhn\fhir\parser\ParserState.java
> needs to be tweaked to make this a working function. Adding
> "!definition.getName().equals("Bundle") &&
> !myResourceType.getName().contains("Bundle") &&" to the conditional
> statement at line 1079 of the above file would escape the
> DataFormatException "wrongResourceTypeFound" that prevented parsing nested
> bundles.
>
> if (!definition.getName().equals("Bundle") &&
> !myResourceType.getName().contains("Bundle") &&
> !StringUtils.equals(theLocalPart, definition.getName())) {
> throw new DataFormatException(Msg.code(1814)
> + myContext
> .getLocalizer()
> .getMessage(
> ParserState.class,
> "wrongResourceTypeFound",
> definition.getName(),
> theLocalPart));
> }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nightingaleproject/VRDR_javalib/pull/57#issuecomment-1652619063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC77B4KNKXW5WRUN2OGFLDXSGKKHANCNFSM6AAAAAA2CE6JZ4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-28 12:50 UTC, consultantusa commented
ParserState has all of its fields as private. Method "enteringNewElement" with the thrown Exception in discussion actually belongs to abstract class BasePreResourceState that resides in the same java file ParseState.java. I am working on the issue and also exploring alternatives.

2023-08-02 03:55 UTC, merged